[package]
name = "plugin-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
picoplugin = { path = "/home/dimas/picodata/picodata/picoplugin" }
linkme = "0.3.14"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["lib", "cdylib"]
